allow merging the master branch into the release branch

diff --git a/performRelease/createTag b/performRelease/createTag
--- a/performRelease/createTag
+++ b/performRelease/createTag
@@ -4,6 +4,20 @@ set -e
 
 . profile
 
+usage() { echo "Usage: $0 [-m]" 1>&2; exit 1; }
+
+while getopts ":m" o; do
+   case "$o" in
+      m)
+         MERGE=1
+         ;;
+      *)
+         usage
+         ;;
+   esac
+done
+shift $((OPTIND-1))
+
 section Create tag: $tag
 
 [ -d workspace ] && die "Workspace still exists"
@@ -24,6 +38,27 @@ for i in $repos; do
 done
 
 mkdir logs
+
+# merge changes from master
+
+if [ ! -z "$MERGE" ]; then
+
+   section Merge from master
+
+   for i in $repos; do
+     repo="org.eclipse.scada.${i}"
+     echo $repo
+     pushd "$repo"
+     msg="`git log -n1 --pretty=format:%s | egrep "^Generate version qualifiers for " `"
+     if [ -z "$msg" ]; then
+        die "Unable to find standard qualifier commit in previous commit. Manual intervention needed!"
+     fi
+     git revert --no-edit HEAD >../logs/merge.${repo}.log
+     git merge origin/master >>../logs/merge.${repo}.log
+     popd
+   done
+
+fi
 
 # set the superParent version
 
