add quiet parameter

diff --git a/org.eclipse.scada.deploy.packages/src/bin/esSetupPostgresDatabase b/org.eclipse.scada.deploy.packages/src/bin/esSetupPostgresDatabase
--- a/org.eclipse.scada.deploy.packages/src/bin/esSetupPostgresDatabase
+++ b/org.eclipse.scada.deploy.packages/src/bin/esSetupPostgresDatabase
@@ -1,14 +1,31 @@
 #!/bin/bash
 
+quiet=0
+
+while getopts "q" opt; do
+  case $opt in
+    q)
+      quiet=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+shift $(( OPTIND - 1 ))
+
 dbName="$1"
 username="$2"
 password="$3"
 
 templateFile="/usr/share/eclipsescada/sql/create.postgres.sql"
 
-test -z "$dbName" && { echo "$0: <dbName> <username> <password>"; exit 1; } 
-test -z "$username" && { echo "$0: <dbName> <username> <password>"; exit 1; }
-test -z "$password" && { echo "$0: <dbName> <username> <password>"; exit 1; }
+test -z "$dbName" && { echo "$0: [-q] <dbName> <username> <password>"; exit 1; } 
+test -z "$username" && { echo "$0: [-q] <dbName> <username> <password>"; exit 1; }
+test -z "$password" && { echo "$0: [-q] <dbName> <username> <password>"; exit 1; }
+
 
 set -e
 
@@ -28,18 +45,26 @@ function hasTables () {
 	return $?
 }
 
+function sql () {
+	if [ $quiet -ne 0 ]; then
+		psql "$@" &>/dev/null
+	else
+		psql "$@"
+	fi
+}
+
 function createUser () {
-	psql -c "CREATE USER $username WITH PASSWORD '$password';" &>/dev/null
+	sql -c "CREATE USER $username WITH PASSWORD '$password';"
 }
 
 function createDatabase () {
-	psql -c "CREATE DATABASE $dbName WITH OWNER $username TEMPLATE template0 ENCODING 'UTF-8' lc_ctype='en_US.utf8' lc_collate='en_US.utf8';" &>/dev/null
+	sql -c "CREATE DATABASE $dbName WITH OWNER $username TEMPLATE template0 ENCODING 'UTF-8' lc_ctype='en_US.utf8' lc_collate='en_US.utf8';"
 }
 
 function createTables () {
-	psql -d eclipsescada -q -f "$templateFile" &>/dev/null
-	psql -d eclipsescada -c "ALTER TABLE es_ae_events_hstore OWNER TO $username;" &>/dev/null
-	psql -d eclipsescada -c "ALTER TABLE es_ae_rep OWNER TO $username;" &>/dev/null
+	sql -d eclipsescada -q -f "$templateFile"
+	sql -d eclipsescada -c "ALTER TABLE es_ae_events_hstore OWNER TO $username;"
+	sql -d eclipsescada -c "ALTER TABLE es_ae_rep OWNER TO $username;"
 }
 
 echo "Database: $dbName"
